version: '3.9'


services:
  bot:
    build: .
    links: 
      - mysql
      - redis

    volumes:
      - ./src:/support-bot/src
      - ./.app-data/telegram-session:/support-bot/.telegram-session

    command: python3 src/main.py

    env_file:
      - .env

    depends_on:
      - mysql
      - redis

  mysql:
    image: "${MYSQL_ENGINE}:${MYSQL_VERSION}"
    restart: always


    env_file:
      - .env
  
    volumes: 
      - .app-data/mysql:/var/lib/mysql
  
  redis:
    image: "redis:${REDIS_VERSION}"
    restart: always

    env_file:
      - .env

    volumes:
      - .app-data/redis/d–∞ta:/root/redis
      - .app-data/redis/redis.conf:/usr/local/etc/redis/redis.conf


  phpmyadmin:
    image: "phpmyadmin:${PMA_VERSION}"
    restart: always

    links: 
      - mysql

    ports:
      - ${PMA_HTTP_PORT}:80

    environment:
      PMA_HOST: mysql


