version: '3.9'


services:
  bot:
    build: .
    links: 
      - redis

    volumes:
      - ./src:/support-bot/src
      - ./.app-data/telegram-session:/support-bot/.telegram-session
      - ./.app-data/sqlite:/support-bot/.app-data/sqlite

    command: python3 src/main.py

    env_file:
      - .env

    depends_on:
      - redis
  
  redis:
    image: "redis:${REDIS_VERSION}"
    restart: always

    env_file:
      - .env

    volumes:
      - .app-data/redis/d–∞ta:/root/redis
      - .app-data/redis/redis.conf:/usr/local/etc/redis/redis.conf
